services:
  backend:
    build: ./
    container_name: andre_backend
    command: ["python",  "manage.py", "runserver", "0.0.0.0:8004"]
    ports:
      - "9004:8004"
    env_file:
      - .env
    volumes:
      - ./:/app/andre
    networks:
      - app_net
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  celery_worker:
    build: ./
    container_name: andre_celery_worker
    env_file:
      - .env
    volumes:
      - ./:/app/andre
    command: ["celery", "-A", "andre", "worker",  "-l", "info"]
    depends_on:
      - backend
  
  celery_beat:  
    build: ./
    container_name: andre_celery_beat
    env_file:
      - .env
    volumes:
      - ./:/app/andre
    command: ["celery", "-A", "andre", "beat",  "-l", "info"]
    depends_on:
      - celery_worker

networks:
  app_net:
    driver: bridge