services:
  backend:
    build: ./
    container_name: andre_backend
    ports:
      - "9004:8004"
    environment:
      - DB_HOST=host.docker.internal
      - DB_NAME=andre_django
      - DB_PASSWORD=Java_123
      - DB_PORT=5432
      - DB_USER=superdbuser
    volumes:
      - ./:/app/andre
    networks:
      - app_net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  celery_worker:
    build: ./
    container_name: andre_celery_worker
    volumes:
      - ./:/app/andre
    command: celery -A andre worker -l info
    depends_on:
      - backend
  
  celery_beat:  
    build: ./
    container_name: andre_celery_beat
    volumes:
      - ./:/app/andre
    command: celery -A andre beat -l info
    depends_on:
      - celery_worker

networks:
  app_net:
    driver: bridge