# Generated by Django 5.2.4 on 2025-08-18 10:22

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftConnectedAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microsoft_id', models.CharField()),
                ('user_principal_name', models.CharField()),
                ('mail_id', models.CharField()),
                ('display_name', models.CharField(null=True)),
                ('surname', models.CharField(null=True)),
                ('given_name', models.CharField()),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField()),
                ('body_preview', models.CharField()),
                ('subject', models.CharField()),
                ('content', models.CharField()),
                ('sender_email', models.CharField(null=True)),
                ('to_recipient_emails', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(null=True), default=list, size=None)),
                ('conversation_id', models.CharField(null=True)),
                ('mail_time', models.DateTimeField(null=True)),
                ('microsoft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microsoft.microsoftconnectedaccounts')),
            ],
        ),
    ]
