# Generated by Django 5.2.4 on 2025-08-23 12:28

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftConnectedAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('display_name', models.CharField(null=True)),
                ('given_name', models.CharField()),
                ('mail_id', models.CharField()),
                ('microsoft_id', models.CharField()),
                ('refresh_token', models.TextField()),
                ('surname', models.CharField(null=True)),
                ('user_principal_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_preview', models.CharField()),
                ('content', models.CharField()),
                ('conversation_id', models.CharField(null=True)),
                ('mail_time', models.DateTimeField(null=True)),
                ('message_id', models.CharField()),
                ('sender_email', models.CharField(null=True)),
                ('subject', models.CharField()),
                ('to_recipient_emails', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(null=True), default=list, size=None)),
                ('unique_body', models.CharField()),
                ('microsoft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_message', to='microsoft.microsoftconnectedaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField()),
                ('end', models.DateTimeField()),
                ('location', models.CharField()),
                ('remainder_minutes_before_start', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('subject', models.CharField()),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='microsoft.emailmessages')),
                ('microsoft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='microsoft.microsoftconnectedaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='Summarization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summarization', to='microsoft.calender')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summarization', to='microsoft.emailmessages')),
                ('microsoft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summarization', to='microsoft.microsoftconnectedaccounts')),
            ],
        ),
    ]
