# Generated by Django 5.2.4 on 2025-08-23 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarization',
            name='calendar',
        ),
        migrations.AddField(
            model_name='calender',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='microsoft.summarization'),
        ),
    ]
