# Generated by Django 5.2.4 on 2025-08-22 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0002_summarization'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarization',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microsoft.emailmessages'),
        ),
        migrations.AddField(
            model_name='summarization',
            name='microsoft',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='microsoft.microsoftconnectedaccounts'),
            preserve_default=False,
        ),
    ]
