# Generated by Django 5.2.4 on 2025-08-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0003_summarization_email_summarization_microsoft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summarization',
            old_name='calender',
            new_name='calendar',
        ),
    ]
