# Generated by Django 5.2.4 on 2025-08-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0003_calender_body_alter_calender_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='subject',
            field=models.CharField(blank=True, null=True),
        ),
    ]
