# Generated by Django 5.2.4 on 2025-08-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0004_rename_calender_summarization_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarization',
            name='calendar',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
