# Generated by Django 5.2.4 on 2025-08-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0004_alter_calender_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessages',
            name='subject',
            field=models.CharField(blank=True, null=True),
        ),
    ]
