# Generated by Django 5.2.4 on 2025-08-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0005_alter_emailmessages_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calender',
            name='summary',
        ),
        migrations.AddField(
            model_name='emailmessages',
            name='reply',
            field=models.CharField(blank=True, null=True),
        ),
    ]
