# Generated by Django 5.2.4 on 2025-08-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0006_remove_calender_summary_emailmessages_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessages',
            name='unique_body',
            field=models.CharField(blank=True),
        ),
    ]
