# Generated by Django 5.2.4 on 2025-08-26 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0007_alter_emailmessages_unique_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField()),
                ('refresh_token', models.CharField()),
                ('microsoft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to='microsoft.microsoftconnectedaccounts')),
            ],
        ),
    ]
