# Generated by Django 5.2.4 on 2025-08-26 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0008_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertoken',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='microsoft',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to='microsoft.microsoftconnectedaccounts'),
        ),
    ]
