# Generated by Django 5.2.4 on 2025-08-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0010_calender_created_calender_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftconnectedaccounts',
            name='folder_id',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microsoftconnectedaccounts',
            name='folder_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
