# Generated by Django 5.2.4 on 2025-08-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0011_microsoftconnectedaccounts_folder_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microsoftconnectedaccounts',
            name='folder_id',
        ),
        migrations.RemoveField(
            model_name='microsoftconnectedaccounts',
            name='folder_name',
        ),
        migrations.AddField(
            model_name='emailmessages',
            name='folder_id',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailmessages',
            name='folder_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
