# Generated by Django 5.2.4 on 2025-08-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0012_remove_microsoftconnectedaccounts_folder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftconnectedaccounts',
            name='container_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
