# Generated by Django 5.2.4 on 2025-08-27 09:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0013_microsoftconnectedaccounts_container_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessages',
            name='attachment_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='emailmessages',
            name='has_attachments',
            field=models.BooleanField(default=False),
        ),
    ]
