# Generated by Django 5.2.4 on 2025-08-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0014_emailmessages_attachment_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessages',
            name='attachment_content_type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
