# Generated by Django 5.2.4 on 2025-08-27 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0015_emailmessages_attachment_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessages',
            name='received_date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 27, 11, 57, 18, 93703, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailmessages',
            name='send_date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 27, 11, 57, 23, 21617, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
