# Generated by Django 5.2.4 on 2025-08-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0016_emailmessages_received_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarization',
            name='summary_type',
            field=models.CharField(choices=[('EML', 'Email'), ('EMA', 'Attachments'), ('DOC', 'Documents')], default='EML', max_length=3),
        ),
    ]
