# Generated by Django 5.2.4 on 2025-08-28 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0017_summarization_summary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessages',
            name='reply_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_message', to='microsoft.emailmessages'),
        ),
    ]
