# Generated by Django 5.2.4 on 2025-08-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0018_emailmessages_reply_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessages',
            name='message_id',
            field=models.CharField(unique=True),
        ),
    ]
