# Generated by Django 5.2.4 on 2025-08-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0020_session_message_vectorstore_session_vector_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectorstore',
            name='vector_store_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
