# Generated by Django 5.2.4 on 2025-08-30 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0021_alter_vectorstore_vector_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='vector_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='microsoft.vectorstore'),
        ),
    ]
