# Generated by Django 5.2.4 on 2025-09-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0022_alter_session_vector_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_name',
            field=models.CharField(default='Demo chat'),
        ),
    ]
