# Generated by Django 5.2.4 on 2025-09-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0023_session_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
