# Generated by Django 5.2.4 on 2025-09-04 09:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft', '0024_session_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessages',
            name='bcc_recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='emailmessages',
            name='cc_recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(null=True), default=list, size=None),
        ),
    ]
