import os

import requests
from dotenv import load_dotenv

load_dotenv()

access_token = os.getenv("ACCESS_TOKEN")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")

endpoint = "https://graph.microsoft.com/v1.0/me/sendMail"

email_msg = {
    "message": {
        "subject": "Hello from Graph API",
        "body": {
            "contentType": "HTML",
            "content": "<p>Hello,</p><p>This is your weekly report generated by our system.</p><p>Thank you,<br>Team</p>"
        },
        "toRecipients": [
            {
                "emailAddress": {
                    "address": EMAIL_HOST_USER
                }
            }
        ]
    }
}

response = requests.post(
    endpoint,
    headers={"Authorization": f"Bearer {access_token}"},
    json=email_msg,
)

if response.status_code == 202:
    print("✅ Email sent successfully!", response.content.decode('utf-8'))
else:
    print("❌ Error:", response.status_code, response.text)
